# Generated by Django 4.1.7 on 2023-03-25 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='investor',
            fields=[
                ('investorID', models.UUIDField(primary_key=True, serialize=False)),
                ('investor_name', models.CharField(max_length=100)),
                ('investor_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='startup',
            fields=[
                ('startupID', models.UUIDField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('company_email', models.EmailField(max_length=100, unique=True)),
                ('company_website', models.URLField()),
                ('company_Founders', models.CharField(max_length=100)),
                ('linkedinURL', models.URLField()),
                ('productDescription', models.CharField(max_length=300)),
                ('revenueDescription', models.CharField(max_length=300)),
                ('pitchUpload', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Auctions',
            fields=[
                ('auctionID', models.UUIDField(primary_key=True, serialize=False)),
                ('finalPercent', models.PositiveSmallIntegerField()),
                ('finalPrice', models.PositiveIntegerField()),
                ('startupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.startup')),
            ],
        ),
    ]
