# Generated by Django 4.1.7 on 2023-03-25 13:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_rename_auctions_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auctionID',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='investor',
            name='investorID',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='startup',
            name='startupID',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
